#!/usr/bin/env bash

if [ $# -gt 0 ]
then
	logfile=${1}
else
	if [ -z ${NOWLIVELOGFILE} ]
	then
		echo "No logfile provided and Environment variables not set. Run ' . nowliveenv.sh' to set them"
		exit
	else
		logfile=${NOWLIVELOGFILE}
	fi
fi

if [ -f ${logfile} ]
then
#	total=$(grep -c 2019 ${logfile})
	total=$(grep 2019 ${logfile} | grep -c "	live")
	rerun=$(grep 2019 ${logfile} | grep -c "	rerun")
	missed=$(grep 2019 ${logfile} | grep -c "	missed")
	dupes=$(grep 2019 ${logfile} | grep -c "	multiple")
	echo "live: $total reruns: $rerun missed: $missed dupes: $dupes"
else
	echo "${logfile} not found"
fi

