#!/usr/bin/env bash

cmd=$(basename $0)

if [ $# -gt 0 ]
then
	logfile=${1}
else
	if [ -z ${NOWLIVELOGFILE} ]
	then
		echo "No logfile provided and Environment variables not set. Run ' . nowliveenv.sh' to set them"
		exit
	else
		logfile=${NOWLIVELOGFILE}
	fi
	#logfile="logs/twitch_twitter.log"
fi

if [ -f ${logfile} ]
then
	if [ ${cmd} = "showtweets" ]
	then
		grep "^20" ${logfile} # this stops working in 2100. plan accordingly.
	else
		cat ${logfile}
	fi
else
	echo "${logfile} not found"
fi

